# Generated by Django 4.2.6 on 2023-10-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'Level A'), ('B', 'Level B')], max_length=1)),
                ('spot_number', models.IntegerField(unique=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'parkingspot',
            },
        ),
    ]
